#!/bin/bash

# Easier navigation: .., ..., ...., ..... and ~
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias g="git"
alias h="history"
alias hosts='sudo $EDITOR /etc/hosts'   # yes I occasionally 127.0.0.1 twitch.tv ;)
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias j="jobs"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias rm="rm -rf --"
alias t="tmux"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# List all files colorized in long format

alias l="ls -lp"

# List all files colorized in long format, including dot files

alias la="ls -lap"

# List all hidden files colorized in long format

alias l.="ls -ldp .*"

# List only directories

alias lsd='ls -lF | grep "^d"'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "$OS/bash_aliases"
