#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen.

alias afk="osascript -e 'tell application \"System Events\" to sleep'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for `Homebrew`.

alias brewd="brew doctor"
alias brewi="brew install"
alias brewr="brew uninstall"
alias brews="brew search"
alias brewu="brew update --quiet \
                && brew upgrade \
                && brew cleanup"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# `cat` with beautiful colors.

alias cat='bat --paging=never --style=plain'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description

alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | \
                   grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear DNS cache.

alias clear-dns-cache="sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Recursively delete `.DS_Store` files

alias cleanup="fd . -type f -name '*.DS_Store' -ls -delete"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty the trash, the main HDD and on all mounted volumes,
# and clear Apple’s system logs to improve shell startup speed.

alias empty-trash="sudo rm -frv /Volumes/*/.Trashes; \
                   sudo rm -frv ~/.Trash; \
                   sudo rm -frv /private/var/log/asl/*.asl; \
                   sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show desktop icons.

alias hide-desktop-icons="defaults write com.apple.finder CreateDesktop -bool false \
                            && killall Finder"

alias show-desktop-icons="defaults write com.apple.finder CreateDesktop -bool true \
                            && killall Finder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Show/hide hidden files in Finder

alias show-files="defaults write com.apple.finder AppleShowAllFiles -bool true \
                    && killall Finder"

alias hide-files="defaults write com.apple.finder AppleShowAllFiles -bool false \
                    && killall Finder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP.

alias local-ip="ipconfig getifaddr en1"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clean up LaunchServices to remove duplicates in the “Open With” menu

alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open from the terminal.

alias o="open"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Reload the shell (i.e. invoke as a login shell)

alias reload="exec $SHELL -l"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Disable/Enable Spotlight

alias spot-off="sudo mdutil -a -i off"

alias spot-on="sudo mdutil -a -i on"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Stopwatch

alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update applications and CLTs.

alias update="sudo softwareupdate --install --all \
            && brew update \
            && brew upgrade \
            && brew cleanup"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get week number
alias week='date +%V'
